runtime: python37

entrypoint: gunicorn -b :8080 'app:create_app()'

handlers:
    # This configures Google App Engine to serve the files in the app's static
    # directory.
  - url: /static
    static_dir: app/static

  - url: /images
    static_dir: app/static/img

  - url: /css
    static_dir: app/static/css

  - url: /js
    static_dir: app/static/js

    # This handler routes all requests not caught above to your main app. It is
    # required when static routes are defined
  - url: /app/.*
    script: auto

